# Generated by Django 5.0.4 on 2024-04-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('name', models.CharField(max_length=22, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=22, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=55, primary_key=True, serialize=False, verbose_name='Class ID')),
                ('room_name', models.CharField(max_length=255, unique=True, verbose_name='Class Name')),
                ('room_count', models.PositiveIntegerField(default=0)),
                ('room_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.parent', verbose_name='Class Representative')),
                ('room_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.teacher', verbose_name='Class Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('stream_name', models.CharField(max_length=255, unique=True)),
                ('stream_prefect', models.CharField(blank=True, max_length=255, null=True)),
                ('stream_count', models.PositiveIntegerField(default=0)),
                ('stream_representative', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.parent')),
                ('stream_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.room')),
                ('stream_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.teacher')),
            ],
        ),
    ]
