# Generated by Django 5.0.4 on 2024-04-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0002_student_alter_stream_stream_prefect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.teacher'),
        ),
    ]
