# Generated by Django 5.0.4 on 2024-04-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRoom', '0002_alter_room_room_representative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.parent'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassRoom.teacher'),
        ),
    ]
